# Generated by Django 5.1.5 on 2025-02-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LLMResponse',
        ),
    ]
