# Generated by Django 5.1.6 on 2025-02-26 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0002_remove_llm_session_id_alter_llm_session_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llm_config',
            name='session',
        ),
    ]
