# Generated by Django 5.1.5 on 2025-02-13 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0002_delete_llmresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLM_Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('model_url', models.CharField()),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=512)),
            ],
        ),
        migrations.CreateModel(
            name='LLM_Interaction_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('request', models.TextField()),
                ('response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request_type', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice')], default='text', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LLM_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('user_id', models.IntegerField()),
                ('pergunta', models.TextField()),
                ('resposta', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LLM_Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('user_id', models.IntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('model_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pools.llm_config')),
            ],
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='session',
        ),
        migrations.DeleteModel(
            name='LLMConfig',
        ),
        migrations.DeleteModel(
            name='LLMRequest',
        ),
        migrations.DeleteModel(
            name='UsageLog',
        ),
        migrations.AddField(
            model_name='llm_interaction_log',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.llm_session'),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
    ]
