# Generated by Django 5.1.6 on 2025-03-18 18:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_empresas_remove_user_info_user_usuarios'),
        ('pools', '0003_remove_llm_config_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llm_session',
            name='model_config',
        ),
        migrations.RemoveField(
            model_name='llm_interaction_log',
            name='session',
        ),
        migrations.RemoveField(
            model_name='llm_interaction_log',
            name='user',
        ),
        migrations.RemoveField(
            model_name='llm_request',
            name='session',
        ),
        migrations.RemoveField(
            model_name='llm_request',
            name='user',
        ),
        migrations.RemoveField(
            model_name='llm_session',
            name='user',
        ),
        migrations.CreateModel(
            name='config_model',
            fields=[
                ('config', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=255)),
                ('url_modelo', models.CharField(max_length=255)),
                ('temperatura', models.FloatField()),
                ('num_tokens', models.IntegerField()),
                ('prompt', models.TextField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.empresas')),
            ],
        ),
        migrations.CreateModel(
            name='config_session',
            fields=[
                ('session', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('id_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.config_model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='chat_model',
            fields=[
                ('chat', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.config_session')),
            ],
        ),
        migrations.DeleteModel(
            name='LLM_Config',
        ),
        migrations.DeleteModel(
            name='LLM_Interaction_Log',
        ),
        migrations.DeleteModel(
            name='LLM_Request',
        ),
        migrations.DeleteModel(
            name='LLM_Session',
        ),
    ]
