# Generated by Django 5.1.5 on 2025-02-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0003_llm_config_llm_interaction_log_llm_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llm_request',
            name='session_id',
            field=models.CharField(max_length=255),
        ),
    ]
