# Generated by Django 5.1.6 on 2025-03-20 02:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0004_remove_llm_session_model_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config_model',
            name='schema',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config_model',
            name='tabelas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='config_model',
            name='modelo',
            field=models.CharField(default='llama3', max_length=255),
        ),
        migrations.AlterField(
            model_name='config_model',
            name='num_tokens',
            field=models.IntegerField(default='100'),
        ),
        migrations.AlterField(
            model_name='config_model',
            name='prompt',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='config_model',
            name='temperatura',
            field=models.FloatField(default='0.1'),
        ),
        migrations.AlterField(
            model_name='config_model',
            name='url_modelo',
            field=models.CharField(default='https://www.llama.com', max_length=255),
        ),
    ]
