# Generated by Django 5.1.6 on 2025-02-18 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0005_user_info_llm_config_session_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='llm_interaction_log',
            old_name='session_id',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='llm_request',
            old_name='session_id',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='llm_request',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='llm_session',
            old_name='session_id',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='llm_session',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user_info',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='llm_interaction_log',
            name='user_id',
        ),
        migrations.AddField(
            model_name='llm_config',
            name='prompt',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='llm_interaction_log',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pools.user_info'),
        ),
    ]
