# Generated by Django 5.1.6 on 2025-03-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0005_config_model_schema_config_model_tabelas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config_model',
            name='db_uri',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='config_model',
            name='modelo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='config_model',
            name='url_modelo',
            field=models.CharField(max_length=255),
        ),
    ]
