# Generated by Django 5.1.6 on 2025-03-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0006_config_model_db_uri_alter_config_model_modelo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config_session',
            old_name='id_config',
            new_name='config',
        ),
    ]
