# Generated by Django 5.1.6 on 2025-03-18 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_info_email_alter_user_info_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('prefeitura', 'Prefeitura'), ('estado', 'Estado'), ('federal', 'Federal'), ('ong', 'Ong'), ('outros', 'Outros')], default='outros', max_length=100)),
                ('plano', models.CharField(choices=[('simples', 'Simples'), ('avancado', 'Avançado'), ('completo', 'Completo')], default='simples', max_length=100)),
                ('telefone', models.CharField(max_length=15, unique=True)),
                ('data_adesão', models.DateTimeField(auto_now_add=True)),
                ('imagem', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='user',
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('user', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15, unique=True)),
                ('tipo', models.CharField(choices=[('view', 'View'), ('edit', 'Edit'), ('admin', 'Admin'), ('owner', 'Owner')], default='view', max_length=100)),
                ('primeiro_acesso', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acesso', models.DateTimeField(auto_now_add=True)),
                ('imagem', models.BinaryField(blank=True, null=True)),
                ('password', models.CharField(max_length=128)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.empresas')),
            ],
        ),
    ]
