# Generated by Django 5.1.6 on 2025-03-18 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_empresas_remove_user_info_user_usuarios'),
        ('pools', '0004_remove_llm_session_model_config_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Info',
        ),
    ]
