# Generated by Django 5.1.6 on 2025-03-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usuarios_groups_usuarios_is_active_usuarios_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
